### ISSUE TITLE
Create import accounts/import process

### ISSUE THREAD

**Issue by laurencjay** [developmentseed/zambia-buildings-import#10]
Create designated import accounts for the Zambia import

**Comment by laurencjay** [comment]
@kamicut and @smit1678  

The files have been uploaded and readied for import. Here is how I would like to conduct the import process:

<b>1.</b>Please make an import account, follow my naming convention so use your OSM username_zambiabuildings

Such as: `laurencjay_zambiabuildings`

<b>2.</b>Download JOSM if you don't already have it 

<b>3.</b>Files have already been checked for errors, but for peace of mind, please run the JOSM validator tool one more time 
![monosnap 2015-11-04 17-30-13](https://cloud.githubusercontent.com/assets/8364411/10954154/c7b8246e-8319-11e5-822b-92ab5f9c8e69.jpg)

<b>4.</b>Turn on the bing basemap imagery and ensure the offset lines up with our dataset (spot check the dataset.) Generally speaking, there are going to be some offset errors particularly in the south. 

If you notice a slight offset between the bing basemap and the building data, that's ok, and you can leave the data alone. 

If there is a more significant offset, turn on the OSM layer and check to see if there is a GPS trace nearby that we can adjust to, use the select tool to select the buildings you want to move and drag the houses to their new location. (<b> NOTE THIS IS VERY SENSITIVE AND WILL HIGHLIGHT INDIVIDUAL NODES, Please do this VERY CAREFULLY</b>) If you don't see any GPS traces nearby in the OSM data, adjust the offset to overlay with the bing basemap.

![java openstreetmap editor 2015-11-05 18-26-59](https://cloud.githubusercontent.com/assets/8364411/10984904/e4ec2f18-83ea-11e5-846e-849ec947956a.jpg)

(See above select objects button is circled, and the objects in red on the screen are what selected buildings look like)

<b>5.</b>Once the imagery offsets have been made and you're sure that all errors have been validated, you are ready to import the dataset
-Go to File > Upload data in JOSM
-It's going to come up with the pop up below, ignore it and press continue 

![download](https://cloud.githubusercontent.com/assets/8364411/10955099/928aaa4a-831f-11e5-8974-e9c363343e2f.jpg)
-Wait a bit, and then a popup will show up, asking you to add any necessary comments, I suggest the information I have provided below 
![2015-11-04 18-13-37](https://cloud.githubusercontent.com/assets/8364411/10955173/ecb72b06-831f-11e5-9484-f29f39a0b703.jpg)

*Note: This process will take awhile, just let it run in the background while you work on other things. 

@smit1678 and I will be meeting tomorrow morning about conducting the import so we will keep you posted on when to start.

**Comment by laurencjay** [comment]
@bchen10 Selection 2
@jflasher Selection 3
@drewbo Selection 4
@olafveerman Selection 5
@DylanMoriarty Selection 6 
@kamicut Selection 7
@smit1678 Selection 8

**Comment by laurencjay** [comment]
Note everyone participating in the import process, I have updated the ticket above to reflect the process of how you should conduct offsetting the vector imagery. If you have any questions about this, please message me on slack tonight. @bchen10 I have already fixed yours for you. 

Based on this new process, you WILL need to save your OSM file, so make sure you do that before you import the data. 

Thanks all again for helping me with this!

@jflasher @drewbo @olafveerman @DylanMoriarty @kamicut @smit1678

**Comment by laurencjay** [comment]
@jflasher @smit1678 @kamicut @DylanMoriarty @bchen10 @drewbo @olafveerman 

Please update in this ticket once your upload is complete so I can check the data on OSM.

Thanks so much!

**Comment by bchen10** [comment]
I think I'm done updating! Please check! @laurencjay

**Comment by DylanMoriarty** [comment]
I believe mine just finished being uploaded. Party!

**Comment by olafveerman** [comment]
Done here as well.

**Comment by jflasher** [comment]
:100: finished.

**Comment by drewbo** [comment]
:boom: done

**Comment by kamicut** [comment]
[Section 7](http://www.openstreetmap.org/user/kamicut_zambiabuildings/history#map=9/-11.4329/29.9007) done :boom: 

My upload took around 3 hours to complete. I'm not sure that this is less than all the other imports because they're of varying total size, but I did do something extra that possibly lowers the upload time. JOSM can't upload 240K objects in one changeset, so it defaults to making 240K requests to the OSM server. You can reduce that in 'advanced configuration' before clicking 'Upload Changes'. I chose 25 requests of 10,000 objects each. JOSM will ultimately make 5 OSM changesets, but upload 10K objects at a time.

<img width="401" alt="screen_shot_2015-11-08_at_8_36_35_pm" src="https://cloud.githubusercontent.com/assets/719357/11026308/d96b8764-8675-11e5-8748-005ec960cb71.png">

<img width="421" alt="screen_shot_2015-11-08_at_8_36_59_pm" src="https://cloud.githubusercontent.com/assets/719357/11026329/1fed285a-8676-11e5-8420-ade562009486.png">

**Comment by laurencjay** [comment]
@DylanMoriarty @bchen10 @olafveerman @jflasher @drewbo @kamicut @smit1678 

Could you please add the line below to the description in your upload account.

Thanks!

This is a user account for a data upload project. Please reference the OSM wiki for more info: http://wiki.openstreetmap.org/wiki/Northern_Zambia_Buildings_Import

**Comment by drewbo** [comment]
@laurencjay how do I edit my upload account description?

**Comment by laurencjay** [comment]
@drewbo upper left hand corner, click on your user name -->my profile-->my settings and scroll to the bottom

**Comment by drewbo** [comment]
Awesome, thanks + done.

**Comment by laurencjay** [comment]
![openstreetmap 2015-11-20 14-27-53](https://cloud.githubusercontent.com/assets/8364411/11309641/f7097be8-8f92-11e5-86bd-31ad2bf6be80.jpg)

Confirmed the re-upload of Olaf's section looks good live! Closing this ticket, all discussion of uploading/fixing building overlaps will continue on #11.
