### ISSUE TITLE
Failed upload

### ISSUE THREAD

**Issue by olafveerman** [developmentseed/zambia-buildings-import#12]
So... for some reason my import got messed up. Instead of full polygons, the upload added only the nodes of each building. Resulting in this:

![image](https://cloud.githubusercontent.com/assets/751330/11122198/2c2e687c-8928-11e5-9827-61a28b24b1e5.png)

My initial uploads were added through 3 different changesets.

| Original changeset | # nodes added | Revert changeset | # nodes reverted |
| --- | --- | --- | --- |
| [#35128454](https://www.openstreetmap.org/changeset/35128454) | 50001 | [#35244022](https://www.openstreetmap.org/changeset/35244022) | 28314 |
| [#35133348](https://www.openstreetmap.org/changeset/35133348) | 1632 | [#35241511](https://www.openstreetmap.org/changeset/35241511) | 1632 |
| [#35133937](https://www.openstreetmap.org/changeset/35133937) | 33111 | [#35253299](https://www.openstreetmap.org/changeset/35253299) | 33111 |

_For a full list, see [my profile page](https://www.openstreetmap.org/user/Olaf%20Veermann/history#map=10/-10.2717/29.0506)_

While I was able to revert a lot of the erroneous nodes using a [revert script](https://github.com/woodpeck/osm-revert-scripts), I wasn't able to fully revert the first changeset. Running the script a second time on the same changeset doesn't work, resulting in these errors for the non-reverted nodes:

```
GET http://api.openstreetmap.org/api/0.6/node/3821043733/history... 200 OK (428b)
node 3821043733 was created; deleting
DELETE http://api.openstreetmap.org/api/0.6/node/3821043733... 409 Conflict (60b)
node 3821043733 cannot be deleted: 409 Conflict
```

@kamicut What's the most elegant way to tackle this? Diff both changesets for the remaining nodes and then batch delete them?

**Comment by kamicut** [comment]
Yikes, OSM reverts are a tricky business @olafveerman. If the first changeset is just nodes, I think diffing the changesets would be the best way. Do you need help doing this?

**Comment by olafveerman** [comment]
Thanks @kamicut 
Luckily they are all nodes and created from scratch. It should make the process easier.
I'll do the diffing, but will get back to about the deletion

**Comment by olafveerman** [comment]
@kamicut Let's talk about deletion when you get back to the office.

[This script](https://gist.github.com/olafveerman/da64dd90a2b0c315f263) generates a list of diffed node id's

**Comment by olafveerman** [comment]
It's done. The remaining 21687 nodes were deleted in [changeset #35271390](https://www.openstreetmap.org/changeset/35271390).

These were the steps I followed:
- open a changeset using `$ perl changeset.pl create` from the [OSM revert scripts](https://github.com/woodpeck/osm-revert-scripts). This opens a changeset and returns an ID
- generate a OSM Changefile (osc) with the changeset ID generated in the first step, using [this script](https://gist.github.com/olafveerman/da64dd90a2b0c315f263). The output looks along these lines  

``` xml
<osmChange version="0.6" generator="script">
  <delete>
    <node id="3820975442" changeset="35271390" version="1" visible="false" />
  </delete>
  <delete>
    <node id="3820975443" changeset="35271390" version="1" visible="false" />
  </delete>
  ...
</osmChange>
```
- post the OSC file to the OSM upload endpoint using Postman
- close the original changeset `$ perl changeset.pl close 35271390`

@laurencjay

**Comment by laurencjay** [comment]
Awesome great news. Thanks @olafveerman for fixing all this. I'm going to look over your portion again, and then I"ll run the import.
:+1:

**Comment by laurencjay** [comment]
Closing, refer to #10, this issue has been resolved
