### ISSUE TITLE
Create wiki page

### ISSUE THREAD

**Issue by smit1678** [developmentseed/zambia-buildings-import#4]
We've drafted a [final proposal](https://github.com/developmentseed/zambia-buildings-import/blob/master/PROPOSAL.md), ready to make a wiki page

**Comment by laurencjay** [comment]
Wiki page completed: http://wiki.openstreetmap.org/wiki/Northern_Zambia_Buildings_Import
Also located in the import catalogue: http://wiki.openstreetmap.org/wiki/Import/Catalogue
