### ISSUE TITLE
Conduct sample import

### ISSUE THREAD

**Issue by laurencjay** [developmentseed/zambia-buildings-import#9]
Conduct an import of a small amount of the houses data to test the import process

**Comment by smit1678** [comment]
Initial import conducted by @laurencjay and user:`laurencjay_zambiabuildings`went great in the [Mkushi area](https://www.openstreetmap.org/#map=15/-13.6154/29.3969). 

![](https://api.monosnap.com/rpc/file/download?id=P2MxCaxGrGIjCXKrDLNPYgmadVTnKm)

We identified some errors and have manually fixed. Before we continue the upload, we'll look at #2 and #11 to QA and test the source dataset once more before continuing to do more areas.

**Comment by laurencjay** [comment]
Closing this ticket, test import has been conducted. Referencing ticket #11 to go back through the data in a few weeks to rectify remaining issues with the test import.
